### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by jfgugel** [smith-chem-wisc/AppleTurnover#2]

**Comment by jfgugel** [comment]
Hello, I am following the tutorial provided in the article "An atlas of protein turnover rates in mouse tissues." I have successfully followed the tutorial instructions through step 2.5 but cannot complete step 2.6 because Apple Turnover will not open. Any advice?

**Comment by zrolfs** [comment]
Hi jfgugel,
Thanks for your interest! Sorry to hear you haven't been able to open the program.
I just ran through the steps and confirmed that the software program hosted on the MassIVE site still works on my machine, so I suspect there's an issue with the environment you're running.

Currently, I believe this program can only be run on Windows. If you're using a different operating system, please try to open the program on a Windows computer.
 
If it's not working on a Windows computer, you may also need to install .NET Core 5.0:
[https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.4-windows-x64-installer](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.4-windows-x64-installer)
A restart may be required after download.

Please keep me posted; I'd like you to be able to use the software!
Zach

**Comment by jfgugel** [comment]
Hi Zach,

Thank you for the quick reply! I tried installing .NET Core 5.0 and
restarting and it still isn't working for me.

I get to the point in this screenshot and then when I click the
AppleTurnover application nothing happens. Let me know if you have any
other ideas of what might be going wrong.

By the way, this was a super cool paper and I'm very excited that you
created this resource!

Jack Gugel
Leinwand Lab
University of Colorado  Boulder

[image: image.png]

**Comment by jfgugel** [comment]
I just tried it again on a different Windows device and had the same
problem there.

Jack

**Comment by zrolfs** [comment]
Thanks for your patience. I was able to reproduce this issue on my wife's computer. It looks like I wrote this program with .NET Core 3.1 and unfortunately 5.0 doesn't give backwards compatibility. I was able to open the program after downloading 3.1, which you can find here: https://dotnetwebsite-dev.int-dot.net/en-us/download/dotnet/3.1

I didn't need to restart the machine for the fix to work.
![image](https://user-images.githubusercontent.com/16883585/154138213-f4de2c9f-5c6d-4b0c-87e1-429d1ac1cf57.png)

Hopefully this works for you, too! Let me know if not, though. I can escalate this to people who know more than I do.

Best,
Zach

**Comment by jfgugel** [comment]
Zach,

Installing .NET Core 3.1 did the trick! Thank you so much for the support.

Jack
